version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache-
      - run: chmod +x ./scripts/install_gsl.sh && ./scripts/install_gsl.sh
      - run: bundle check || bundle install --frozen
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: git config --global user.name "aloerina01"
      - run: git config --global user.email "4443321+aloerina01@users.noreply.github.com"
      - run: bundle exec rake deploy --trace
  indexing:
    working_directory: ~/workspace
    docker:
      - image: circleci/ruby:2.5.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache-
      - run: chmod +x ./scripts/install_gsl.sh && ./scripts/install_gsl.sh
      - run: bundle check || bundle install --frozen
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: ALGOLIA_API_KEY=$ALGOLIA_ADMIN_API_KEY bundle exec jekyll algolia
workflows:
  version: 2
  build_and_indexing:
    jobs:
      - build
      - indexing:
          requires:
            - build