name: BUILD_AND_DEPLOY

on: 
  push:
    branches:
      - development
      - gh-actions/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6.5'
    - name: Install gsl
      run: chmod +x ./scripts/install_gsl.sh && ./scripts/install_gsl.sh
      run: bundle check --path vendor/bundle || bundle install --frozen --path vendor/bundle && bundle package --all
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.