name: DEPLOY

on: 
  push:
    branches:
      - development
      - gh-actions/*

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
    - name: Install gsl
      run: chmod +x ./scripts/install_gsl.sh && ./scripts/install_gsl.sh
    - name: Bundle install
      run: bundle check --path vendor/bundle || bundle install --frozen --path vendor/bundle && bundle package --all
    - name: execute raketsk (build, commit and push master branch)
      run: |
        git config --global user.name "aloerina01"
        git config --global user.email "4443321+aloerina01@users.noreply.github.com"

  indexing:
    name: Indexing into Algolia
    needs: deploy
    runs-on: ubuntu-latest
    if: <secrets.AlgoliaAdminAPIToken>
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1
      - name: Install gsl
        run: chmod +x ./scripts/install_gsl.sh && ./scripts/install_gsl.sh
      - name: Bundle install
        run: bundle check --path vendor/bundle || bundle install --frozen --path vendor/bundle && bundle package --all
      - name: Indexing
        run: echo hoge
      
      