name: Renovate
on:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Renovate
        uses: renovatebot/github-action@v25.25.2
        with:
          configurationFile: ./.github/renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}